CREATE TABLE public.asset (
	id serial NOT NULL,
	symbol varchar NOT NULL,
	company_name varchar NOT NULL,
	exchange varchar NOT NULL,
	is_valid boolean DEFAULT true NOT NULL,
	CONSTRAINT asset_pk PRIMARY KEY (id),
	CONSTRAINT asset_unique UNIQUE (symbol)
);

INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('OEDV' , 'Osage Exploration and Development, Inc.' , 'PNK' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AAPL' , 'Apple Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BAC' , 'Bank of America Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMZN' , 'Amazon.com, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('T' , 'AT&T Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('GOOG' , 'Alphabet Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('MO' , 'Altria Group, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('DAL' , 'Delta Air Lines, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AA' , 'Alcoa Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AXP' , 'American Express Company' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('DD' , 'E. I. du Pont de Nemours and Company' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BABA' , 'Alibaba Group Holding Limited' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABT' , 'Abbott Laboratories' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('UA' , 'Under Armour, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMAT' , 'Applied Materials, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMGN' , 'Amgen Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AAL' , 'American Airlines Group Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AIG' , 'American International Group, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALL' , 'The Allstate Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADBE' , 'Adobe Systems Incorporated' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('GOOGL' , 'Alphabet Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACN' , 'Accenture plc' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABBV' , 'AbbVie Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('MT' , 'ArcelorMittal' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('LLY' , 'Eli Lilly and Company' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AGN' , 'Allergan plc' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APA' , 'Apache Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADP' , 'Automatic Data Processing, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APC' , 'Anadarko Petroleum Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AKAM' , 'Akamai Technologies, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('NLY' , 'Annaly Capital Management, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABX' , 'Barrick Gold Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATVI' , 'Activision Blizzard, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADSK' , 'Autodesk, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADM' , 'Archer-Daniels-Midland Company' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('WBA' , 'Walgreens Boots Alliance, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARNA' , 'Arena Pharmaceuticals, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('LUV' , 'Southwest Airlines Co.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACAD' , 'ACADIA Pharmaceuticals Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('PANW' , 'Palo Alto Networks, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMD' , 'Advanced Micro Devices, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AET' , 'Aetna Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AEP' , 'American Electric Power Company, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALXN' , 'Alexion Pharmaceuticals, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CLMS' , 'Calamos Asset Management Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVGO' , 'Broadcom Limited' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('EA' , 'Electronic Arts Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('DB' , 'Deutsche Bank Aktiengesellschaft' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('RAI' , 'Reynolds American Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AEM' , 'Agnico Eagle Mines Limited' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APD' , 'Air Products and Chemicals, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMBA' , 'Ambarella, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('NVS' , 'Novartis AG' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APOL' , 'Apollo Education Group, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANF' , 'Abercrombie & Fitch Co.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('LULU' , 'Lululemon Athletica Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('RAD' , 'Rite Aid Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARRY' , 'Array BioPharma Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AGNC' , 'AGNC Investment Corp.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('JBLU' , 'JetBlue Airways Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('A' , 'Agilent Technologies, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ORLY' , 'O Reilly Automotive, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('FOLD' , 'Amicus Therapeutics, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AZO' , 'AutoZone, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATML' , 'Atmel Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AN' , 'AutoNation, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AZN' , 'AstraZeneca PLC' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AES' , 'The AES Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('GAS' , 'AGL Resources Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BUD' , 'Anheuser-Busch InBev SA/NV' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARR' , 'ARMOUR Residential REIT, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BDX' , 'Becton, Dickinson and Company' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AKS' , 'AK Steel Holding Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AB' , 'AllianceBernstein Holding L.P.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACOR' , 'Acorda Therapeutics, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CS' , 'Credit Suisse Group AG' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AFL' , 'Aflac Incorporated' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADI' , 'Analog Devices, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AEGR' , 'Aegerion Pharmaceuticals, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACIW' , 'ACI Worldwide, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMP' , 'Ameriprise Financial, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVP' , 'Avon Products, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMTD' , 'TD Ameritrade Holding Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AEO' , 'American Eagle Outfitters, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AWK' , 'American Water Works Company, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('NVO' , 'Novo Nordisk A/S' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALTR' , 'Altera Corp.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALK' , 'Alaska Air Group, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('PAA' , 'Plains All American Pipeline, L.P.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARCC' , 'Ares Capital Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AAP' , 'Advance Auto Parts, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('NAT' , 'Nordic American Tankers Limited' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('FNMA' , 'Federal National Mortgage Association' , 'PNK' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('FAV' , 'First Trust Dividend and Income Fund' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AIV' , 'Apartment Investment and Management Company' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AGIO' , 'Agios Pharmaceuticals, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AEE' , 'Ameren Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('UBS' , 'UBS Group AG' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVXL' , 'Anavex Life Sciences Corp.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARLP' , 'Alliance Resource Partners, L.P.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANTM' , 'Anthem, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AGU' , 'Agrium Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AG' , 'First Majestic Silver Corp.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AFSI' , 'AmTrust Financial Services, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABC' , 'AmerisourceBergen Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('STO' , 'Statoil ASA' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATI' , 'Allegheny Technologies Incorporated' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADT' , 'The ADT Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVB' , 'AvalonBay Communities, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATW' , 'Atwood Oceanics, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALNY' , 'Alnylam Pharmaceuticals, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('LH' , 'Laboratory Corporation of America Holdings' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVY' , 'Avery Dennison Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AUY' , 'Yamana Gold Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASH' , 'Ashland Global Holdings Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARMH' , 'ARM Holdings plc' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARIA' , 'ARIAD Pharmaceuticals, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANR' , 'Alpha Natural Resources, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AINV' , 'Apollo Investment Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACXM' , 'Acxiom Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACHN' , 'Achillion Pharmaceuticals, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACET' , 'Aceto Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABMD' , 'ABIOMED, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABM' , 'ABM Industries Incorporated' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('VA' , 'Virgin America Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('LIFE' , 'aTyr Pharma, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATO' , 'Atmos Energy Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARP' , 'Atlas Resource Partners, L.P.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AON' , 'Aon plc' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADXS' , 'Advaxis, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADC' , 'Agree Realty Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APU' , 'AmeriGas Partners, L.P.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('SAVE' , 'Spirit Airlines, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AV' , 'Aviva plc' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AKRX' , 'Akorn, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADS' , 'Alliance Data Systems Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABAX' , 'Abaxis, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AYI' , 'Acuity Brands, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AWH' , 'Allied World Assurance Company Holdings, AG' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASML' , 'ASML Holding N.V.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMT' , 'American Tower Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALDR' , 'Alder Biopharmaceuticals, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACM' , 'AECOM' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('DWA' , 'DreamWorks Animation SKG Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATRS' , 'Antares Pharma, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARW' , 'Arrow Electronics, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARI' , 'Apollo Commercial Real Estate Finance, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARG' , 'Airgas, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AR' , 'Antero Resources Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMCC' , 'Applied Micro Circuits Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMC' , 'AMC Entertainment Holdings, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AL' , 'Air Lease Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AGEN' , 'Agenus Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AAN' , 'Aarons, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('WTR' , 'Aqua America, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('FCAU' , 'Fiat Chrysler Automobiles N.V.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BAH' , 'Booz Allen Hamilton Holding Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AXAS' , 'Abraxas Petroleum Corporation' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVT' , 'Avnet, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALB' , 'Albemarle Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AIZ' , 'Assurant, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('SAIC' , 'Science Applications International Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CAR' , 'Avis Budget Group, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AXLL' , 'Axiall Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AU' , 'AngloGold Ashanti Limited' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARO' , 'Aéropostale, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APH' , 'Amphenol Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANTH' , 'Anthera Pharmaceuticals, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMX' , 'América Móvil, S.A.B. de C.V.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMDA' , 'Amedica Corporation' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AI' , 'Arlington Asset Investment Corp.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABCO' , 'The Advisory Board Company' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('WMC' , 'Western Asset Mortgage Capital Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('JKHY' , 'Jack Henry & Associates, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVAV' , 'AeroVironment, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMKR' , 'Amkor Technology, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALJ' , 'Alon USA Energy, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACH' , 'Aluminum Corporation Of China Limited' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ERC' , 'Wells Fargo Advantage Multi-Sector Income Fund' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APPY' , 'Bioptix, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANAC' , 'Anacor Pharmaceuticals, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AEIS' , 'Advanced Energy Industries, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('Y' , 'Alleghany Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('MTGE' , 'MTGE Investment Corp.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CENX' , 'Century Aluminum Company' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASPS' , 'Altisource Portfolio Solutions S.A.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMRN' , 'Amarin Corporation plc' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMPE' , 'Ampio Pharmaceuticals, Inc.' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMAG' , 'AMAG Pharmaceuticals, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALKS' , 'Alkermes plc' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AFFX' , 'Affymetrix Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADES' , 'Advanced Emissions Solutions, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACAT' , 'Arctic Cat Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AAON' , 'AAON, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('XLRN' , 'Acceleron Pharma Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('VRSK' , 'Verisk Analytics, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('VJET' , 'Voxeljet AG' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('OA' , 'Orbital ATK, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATLS' , 'Atlas Energy Group, LLC' , 'PNK' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APTS' , 'Preferred Apartment Communities, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APO' , 'Apollo Global Management, LLC' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALSK' , 'Alaska Communications Systems Group, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALG' , 'Alamo Group Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AHC' , 'A.H. Belo Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACTG' , 'Acacia Research Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACAS' , 'American Capital, Ltd.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('RBA' , 'Ritchie Bros. Auctioneers Incorporated' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('MAA' , 'Mid-America Apartment Communities, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BAM' , 'Brookfield Asset Management Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATHN' , 'athenahealth, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AT' , 'Atlantic Power Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASX' , 'Advanced Semiconductor Engineering, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARCO' , 'Arcos Dorados Holdings Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANET' , 'Arista Networks, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANCX' , 'Access National Corporation' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AIR' , 'AAR Corp.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AF' , 'Astoria Financial Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('WAB' , 'Westinghouse Air Brake Technologies Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('RS' , 'Reliance Steel & Aluminum Co.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('PKG' , 'Packaging Corporation of America' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CSH' , 'Cash America International, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AXDX' , 'Accelerate Diagnostics, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVHI' , 'AV Homes, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVA' , 'Avista Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATHX' , 'Athersys, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARWR' , 'Arrowhead Pharmaceuticals, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANGI' , 'Angies List, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMG' , 'Affiliated Managers Group, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALSN' , 'Allison Transmission Holdings, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALGN' , 'Align Technology, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AKBA' , 'Akebia Therapeutics, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AGO' , 'Assured Guaranty Ltd.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AEZS' , 'Aeterna Zentaris Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACRX' , 'AcelRx Pharmaceuticals, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ROK' , 'Rockwell Automation Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('GLPI' , 'Gaming and Leisure Properties, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('DNI' , 'Dividend and Income Fund' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AZZ' , 'AZZ Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATRC' , 'AtriCure, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARRS' , 'ARRIS International plc' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARMK' , 'Aramark' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AOS' , 'A. O. Smith Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANFI' , 'Amira Nature Foods Ltd.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMID' , 'American Midstream Partners, LP' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMCX' , 'AMC Networks Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALIM' , 'Alimera Sciences, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALE' , 'ALLETE, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AHT' , 'Ashford Hospitality Trust, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACW' , 'Accuride Corp.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABB' , 'ABB Ltd' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('SPR' , 'Spirit AeroSystems Holdings, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('SEE' , 'Sealed Air Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('RDEN' , 'Elizabeth Arden, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('PAAS' , 'Pan American Silver Corp.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('DLPH' , 'Delphi Automotive PLC' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADAC' , 'Adama Technologies Corporation' , 'PNK' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CBL' , 'CBL & Associates Properties, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BBVA' , 'Banco Bilbao Vizcaya Argentaria, S.A.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AYR' , 'Aircastle Limited' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APOG' , 'Apogee Enterprises, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANDE' , 'The Andersons, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMSC' , 'American Superconductor Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMRS' , 'Amyris, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMED' , 'Amedisys, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALEX' , 'Alexander & Baldwin, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALCO' , 'Alico, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADUS' , 'Addus HomeCare Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACTA' , 'Actua Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACST' , 'Acasti Pharma Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AAWW' , 'Atlas Air Worldwide Holdings, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('WMS' , 'Advanced Drainage Systems, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('PAG' , 'Penske Automotive Group, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('MDRX' , 'Allscripts Healthcare Solutions, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('KLIC' , 'Kulicke and Soffa Industries, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ETH' , 'Ethan Allen Interiors Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AZPN' , 'Aspen Technology, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AXE' , 'Anixter International Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATNY' , 'API Technologies Corp.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APRI' , 'Apricus Biosciences, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMH' , 'American Homes 4 Rent' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AME' , 'AMETEK, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AJG' , 'Arthur J. Gallagher & Co.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AIQ' , 'Alliance Healthcare Services, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AHGP' , 'Alliance Holdings GP, L.P.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AGCO' , 'AGCO Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AERI' , 'Aerie Pharmaceuticals, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACRE' , 'Ares Commercial Real Estate Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABEO' , 'Abeona Therapeutics Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('WAL' , 'Western Alliance Bancorporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('SYT' , 'Syngenta AG' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('SHLM' , 'A. Schulman, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('NOG' , 'Northern Oil and Gas, Inc.' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('HTA' , 'Healthcare Trust of America, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('GIII' , 'G-III Apparel Group, Ltd.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('DAVE' , 'Famous Daves of America, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CVU' , 'CPI Aerostructures, Inc.' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BSI' , 'Alon Blue Square Israel Ltd' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AWAY' , 'HomeAway, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATU' , 'Actuant Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASTI' , 'Ascent Solar Technologies, Inc.' , 'PNK' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AREX' , 'Approach Resources, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARE' , 'Alexandria Real Estate Equities, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANSS' , 'Ansys, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMNB' , 'American National Bankshares Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMBS' , 'Amarantus Bioscience Holdings, Inc' , 'PNK' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALR' , 'Alere Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AIXG' , 'Aixtron SE' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AIN' , 'Albany International Corp.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AHL' , 'Aspen Insurance Holdings Limited' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AGX' , 'Argan, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AEG' , 'AEGON N.V.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADTN' , 'ADTRAN, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADMS' , 'Adamas Pharmaceuticals, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACLS' , 'Axcelis Technologies, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABG' , 'Asbury Automotive Group, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ZX' , 'China Zenix Auto International Limited' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('NXJ' , 'Nuveen New Jersey Quality Municipal Income Fund' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('KS' , 'KapStone Paper and Packaging Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('HOLI' , 'HollySys Automation Technologies, Ltd.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('GPI' , 'Group 1 Automotive, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ENI' , 'Enersis Américas S.A.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BEAV' , 'B/E Aerospace, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AXTA' , 'Axalta Coating Systems Ltd.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AWR' , 'American States Water Company' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AWI' , 'Armstrong World Industries, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVEO' , 'AVEO Pharmaceuticals, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AUO' , 'AU Optronics Corp.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATHM' , 'Autohome Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATAX' , 'America First Multifamily Investors, L.P.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASM' , 'Avino Silver & Gold Mines Ltd.' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AROC' , 'Archrock, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANH' , 'Anworth Mortgage Asset Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALX' , 'Alexanders, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AHS' , 'AMN Healthcare Services Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AGI' , 'Alamos Gold Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AER' , 'AerCap Holdings N.V.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AE' , 'Adams Resources & Energy, Inc.' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('RHHBY' , 'Roche Holding AG' , 'PNK' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('PETX' , 'Aratana Therapeutics, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ODC' , 'Oil-Dri Corporation of America' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('NAO' , 'Nordic American Offshore Ltd.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('KAR' , 'KAR Auction Services, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('HUSA' , 'Houston American Energy Corp.' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('HIVE' , 'Aerohive Networks, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('FMS' , 'Fresenius Medical Care AG & Co. KGAA' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('DOX' , 'Amdocs Limited' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CXW' , 'CoreCivic, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AZUR' , 'Azure Midstream Partners, LP' , 'PNK' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AXS' , 'AXIS Capital Holdings Limited' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AXL' , 'American Axle & Manufacturing Holdings, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AWX' , 'Avalon Holdings Corporation' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVID' , 'Avid Technology, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASNA' , 'Ascena Retail Group, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASGN' , 'On Assignment, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARDX' , 'Ardelyx, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARAY' , 'Accuray Incorporated' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AQXP' , 'Aquinox Pharmaceuticals, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APT' , 'Alpha Pro Tech, Ltd.' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APDN' , 'Applied DNA Sciences, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMBC' , 'Ambac Financial Group, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALGT' , 'Allegiant Travel Company' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALDW' , 'Alon USA Partners, LP' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AIT' , 'Applied Industrial Technologies, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AIRM' , 'Air Methods Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AIMC' , 'Altra Industrial Motion Corp.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AEL' , 'American Equity Investment Life Holding Company' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AEHR' , 'Aehr Test Systems' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADHD' , 'Alcobra Ltd.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACUR' , 'Acura Pharmaceuticals, Inc.' , 'PNK' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACHC' , 'Acadia Healthcare Company, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACFC' , 'Atlantic Coast Financial Corporation' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACCO' , 'ACCO Brands Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABY' , 'Atlantica Yield plc' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('TA' , 'TravelCenters of America LLC' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('RPAI' , 'Retail Properties of America, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('MANH' , 'Manhattan Associates, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('LAMR' , 'Lamar Advertising Company' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('KYN' , 'Kayne Anderson MLP Investment Company' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AXN' , 'Aoxing Pharmaceutical Company, Inc.' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATRO' , 'Astronics Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATNI' , 'ATN International, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARCW' , 'ARC Group Worldwide, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APEI' , 'American Public Education, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AP' , 'Ampco-Pittsburgh Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANIK' , 'Anika Therapeutics, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ANGO' , 'AngioDynamics, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMTG' , 'Apollo Residential Mortgage, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMSG' , 'AmSurg Corp.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMOT' , 'Allied Motion Technologies Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AM' , 'Antero Midstream Partners LP' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALV' , 'Autoliv, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALOG' , 'Analogic Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AKR' , 'Acadia Realty Trust' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AEGN' , 'Aegion Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ZLTQ' , 'ZELTIQ Aesthetics, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('WRLD' , 'World Acceptance Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('UHAL' , 'AMERCO' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('UAMY' , 'United States Antimony Corporation' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('SAH' , 'Sonic Automotive, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('RJET' , 'Republic Airways Holdings Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('NAII' , 'Natural Alternatives International, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AQNM' , 'Aquentium, Inc.' , 'PNK' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CAS' , 'A.M. Castle & Co.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CACC' , 'Credit Acceptance Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATSG' , 'Air Transport Services Group, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASEI' , 'American Science & Engineering Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASB' , 'Associated Banc-Corp' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARTX' , 'Arotech Corporation' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AROW' , 'Arrow Financial Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARCB' , 'ArcBest Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMRK' , 'A-Mark Precious Metals, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALRM' , 'Alarm.Com Holdings, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AHP' , 'Ashford Hospitality Prime, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AGRX' , 'Agile Therapeutics, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AFAM' , 'Almost Family, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADK' , 'AdCare Health Systems, Inc.' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACSF' , 'American Capital Senior Floating, Ltd.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABTL' , 'Autobytel Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABGB' , 'Abengoa SA' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABEV' , 'Ambev S.A.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABCD' , 'Cambium Learning Group, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AAOI' , 'Applied Optoelectronics, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('USAP' , 'Universal Stainless & Alloy Products Inc' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('STFC' , 'State Auto Financial Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('STAY' , 'Extended Stay America, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('SEED' , 'Origin Agritech Limited' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('RGA' , 'Reinsurance Group of America, Incorporated' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('IDSA' , 'Industrial Services of America, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('HART' , 'Harvard Apparatus Regenerative Technology, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CH' , 'Aberdeen Chile Fund, Inc.' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CEA' , 'China Eastern Airlines Corporation Limited' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BREW' , 'Craft Brew Alliance, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AXR' , 'AMREP Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVG' , 'AVG Technologies N.V.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AVD' , 'American Vanguard Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AUDC' , 'AudioCodes Ltd.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATRI' , 'Atrion Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATOS' , 'Atossa Genetics Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARC' , 'ARC Document Solutions, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('APIC' , 'Apigee Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AOSL' , 'Alpha and Omega Semiconductor Limited' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AOI' , 'Alliance One International, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AMWD' , 'American Woodmark Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALXA' , 'Alexza Pharmaceuticals Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ALLY' , 'Ally Financial Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AIRI' , 'Air Industries Group' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AFOP' , 'Alliance Fiber Optic Products Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACGL' , 'Arch Capital Group Ltd.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACFN' , 'Acorn Energy, Inc.' , 'PNK' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABR' , 'Arbor Realty Trust, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ABCB' , 'Ameris Bancorp' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('SAMG' , 'Silvercrest Asset Management Group Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('REXI' , 'Resource America, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('RAIL' , 'FreightCar America, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('NSAM' , 'Northstar Asset Management Group Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('MITT' , 'AG Mortgage Investment Trust, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('LCM' , 'Advent/Claymore Enhanced Growth & Income Fund' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('HASI' , 'Hannon Armstrong Sustainable Infrastructure Capital, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('GOL' , 'GOL Linhas AÃ©reas Inteligentes S.A.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('GIL' , 'Gildan Activewear Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('EAD' , 'Wells Fargo Advantage Funds - Wells Fargo Income Opportunities Fund' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATTO' , 'Atento S.A.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATR' , 'AptarGroup, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ATNM' , 'Actinium Pharmaceuticals, Inc.' , 'ASE' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASTC' , 'Astrotech Corporation' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASR' , 'Grupo Aeroportuario del Sureste, S. A. B. de C. V.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ASC' , 'Ardmore Shipping Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARTNA' , 'Artesian Resources Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ARGS' , 'Argos Therapeutics, Inc.' , 'NGM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AOD' , 'Alpine Total Dynamic Dividend Fund' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AGNCP' , 'AGNC Investment Corp.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ADRO' , 'Aduro BioTech, Inc.' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ACNB' , 'ACNB Corporation' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AAV' , 'Advantage Oil & Gas Ltd.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AAT' , 'American Assets Trust, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('ZNH' , 'China Southern Airlines Company Limited' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('UAM' , 'Universal American Corp.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('NTT' , 'Nippon Telegraph and Telephone Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('NFJ' , 'AllianzGI NFJ Dividend, Interest & Premium Strategy Fund' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('LNT' , 'Alliant Energy Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('KALU' , 'Kaiser Aluminum Corporation' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('HOMB' , 'Home Bancshares, Inc. (Conway, AR)' , 'NMS' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('HIX' , 'Western Asset High Income Fund II Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('FAF' , 'First American Financial Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('FAC' , 'First Acceptance Corporation' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('EGT' , 'Entertainment Gaming Asia Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('CAAS' , 'China Automotive Systems, Inc.' , 'NCM' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BGR' , 'BlackRock Energy and Resources Trust' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('BETR' , 'Amplify Snack Brands, Inc.' , 'NYQ' );
INSERT INTO public.asset (symbol,company_name,exchange) VALUES ('AUPH' , 'Aurinia Pharmaceuticals Inc.' , 'NGM' );


CREATE TABLE public.user_asset (
	id serial NOT NULL,
	symbol varchar(10) NOT NULL,
	display_order int NOT NULL,
	CONSTRAINT user_asset_pk PRIMARY KEY (id),
	CONSTRAINT user_asset_unique UNIQUE (symbol)
);

CREATE TABLE public."users" (
	id serial NOT NULL,
	login varchar NOT NULL,
	"password" varchar NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (id),
	CONSTRAINT user_unique UNIQUE (login)
);

-- id34lCTVM
INSERT INTO public.users (login, password) VALUES ('service-user-1', '$2a$12$R7lfJg.ERBKZshi4yXVYj.DN8vENh09acyBMOHt1gP5/QUlT8IRyq')


