name: CI/CD Pipeline

on:
  push: # Pipeline irá rodar em pushes e pull requests
    branches:
      - main
  pull_request:

jobs:

  test: # Rodar Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn clean test

  docker: # Atualizar versão da imagem no Docker hub
    runs-on: ubuntu-latest

    needs: test

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/esd-service:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/esd-service:latest ${{ secrets.DOCKER_USERNAME }}/esd-service:${{ github.sha }}

      # Step 4: Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/esd-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/esd-service:${{ github.sha }}
