name: CI/CD Pipeline

on:
  push: # Pipeline irá rodar em pushes e pull requests
    branches:
      - main
  pull_request:

jobs:

  test: # Rodar Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn clean test

  docker: # Atualizar versão da imagem no Docker hub
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Set up Maven
      - name: Set up Maven
        uses: s4u/maven-settings-action@v2
        with:
          maven-version: '3.9.4'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fiap-esd-trab2-service:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/fiap-esd-trab2-service:latest ${{ secrets.DOCKER_USERNAME }}/fiap-esd-trab2-service:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fiap-esd-trab2-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fiap-esd-trab2-service:${{ github.sha }}